"""
This type stub file was generated by pyright.
"""

"""
ai-rules-cli - A powerful CLI toolkit for extending and enhancing AI capabilities
through customizable rules and commands.
"""
__version__ = ...
